use_frameworks!

platform :ios, '9.0'

target 'TMAssetLoader_Example' do
  pod 'TMAssetLoader', :path => '../'

#pod 'TMAssetLoader'
  target 'TMAssetLoader_Tests' do
    inherit! :search_paths

    
  end
end
